language: python
python:
  - "3.7"
  - "nightly"
jobs:
  allow_failures:
    - python: "nightly"
install:
  - pip install -e .
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install flake8-docstrings
  - pip install flake8-import-order
  - pip install mypy
  - pip install pep8-naming
  - pip install pycodestyle
  - pip install pylint
script: ./test.sh
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
